server:
  port: 9083
spring:
  application:
    name: provider-hystrix
eureka:
  instance:
    instance-id: provider-hystrix
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
logging:
  file:
    name: ${spring.application.name}.log
  level:
    com.aurora: debug