server:
  port: 9082
spring:
  application:
    name: consumer-single
eureka:
  instance:
    instance-id: consumer-single
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


logging:
  file:
    name: ${spring.application.name}.log
  level:
    com.aurora: debug