server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zbsilent/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
        default-label: main
eureka:
  instance:
    instance-id: cloud-config-center
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/