spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-critical-timeout: "3000s"
        #        catalog-services-watch-delay: 1000
        #        catalog-services-watch-timeout: 2
        #        health-check-timeout: 10000
        enabled: true
        health-check-interval: "1000s"
        health-check-timeout: "2000s"
#    loadbalancer:
#      enabled: true
#      cache:
#        enabled: true
server:
  port: 8005

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: basic
logging:
  file:
    name: ${spring.application.name}.log
  level:
    com.aurora.ofeign.http: debug