server:
  port: 9081
spring:
  application:
    name: provider-single
eureka:
  instance:
    instance-id: provider-single
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true #单节点无所谓 集群必须配置rebbon使用负载均衡