spring:
  cloud:
    loadbalancer:
#      cache:
#        enabled: false
      enabled: true
  application:
    name: cloud-order-service
#  devtools:
#    restart:
#      enabled: true
#    livereload:
#      enabled: true
server:
  port: 8082
eureka:
#  instance:
#    prefer-ip-address: true #使用服务的IP地址注册
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    fetch-registry: true
